name: MGM240P Zigbee
device: MGM240PB32VNA
base_project: src/zigbee_ncp
filename: "{manifest_name}_{ezsp_version}_{fw_variant}_{baudrate}"
sdk: "gecko_sdk:4.4.4"
toolchain: "12.2.1.20221205"

gbl:
  fw_type: zigbee_ncp
  ezsp_version: dynamic
  baudrate: 115200
  fw_variant: sw_flow

configuration:
  EMBER_CHILD_TABLE_SIZE: 32
  SL_IOSTREAM_USART_VCOM_BAUDRATE: 115200
  SL_IOSTREAM_USART_VCOM_FLOW_CONTROL_TYPE: uartFlowControlSoftware

slcp_defines:
  EMBER_ADDRESS_TABLE_SIZE: 32
  EMBER_MULTICAST_TABLE_SIZE: 26
  EMBER_ROUTE_TABLE_SIZE: 16
  EMBER_DISCOVERY_TABLE_SIZE: 8

c_defines:
  EMBER_APS_UNICAST_MESSAGE_COUNT: 64
  EMBER_BINDING_TABLE_SIZE: 32
  EMBER_NEIGHBOR_TABLE_SIZE: 26
  EMBER_BROADCAST_TABLE_SIZE: 64
  EMBER_KEY_TABLE_SIZE: 12
  EMBER_MAX_END_DEVICE_CHILDREN: 32
  EMBER_SOURCE_ROUTE_TABLE_SIZE: 200


  SL_IOSTREAM_USART_VCOM_RX_BUFFER_SIZE: 64

  SL_IOSTREAM_USART_VCOM_PERIPHERAL: USART0
  SL_IOSTREAM_USART_VCOM_PERIPHERAL_NO: 0

  SL_IOSTREAM_USART_VCOM_TX_PORT: gpioPortA
  SL_IOSTREAM_USART_VCOM_TX_PIN:  5

  SL_IOSTREAM_USART_VCOM_RX_PORT: gpioPortA
  SL_IOSTREAM_USART_VCOM_RX_PIN:  6

  SL_IOSTREAM_USART_VCOM_CTS_PORT: 0
  SL_IOSTREAM_USART_VCOM_CTS_PIN:  0

  SL_IOSTREAM_USART_VCOM_RTS_PORT: 0
  SL_IOSTREAM_USART_VCOM_RTS_PIN:  0

