name: SLZB-07Mg24 Zigbee
device: EFR32MG24A020F1024IM40
base_project: src/zigbee_ncp
filename: "{manifest_name}_{ezsp_version}_{baudrate}"
sdk: "gecko_sdk:4.4.6"
toolchain: "12.2.1.20221205"

gbl:
  fw_type: zigbee_ncp
  ezsp_version: dynamic
  baudrate: 115200

slcp_defines:
  
  EMBER_MULTICAST_TABLE_SIZE: 26
  EMBER_ROUTE_TABLE_SIZE: 16
  EMBER_DISCOVERY_TABLE_SIZE: 8

c_defines:
  EMBER_APS_UNICAST_MESSAGE_COUNT: 128
  EMBER_BINDING_TABLE_SIZE: 32
  EMBER_NEIGHBOR_TABLE_SIZE: 26
  EMBER_BROADCAST_TABLE_SIZE: 64
  EMBER_KEY_TABLE_SIZE: 12
  EMBER_MAX_END_DEVICE_CHILDREN: 32
  EMBER_SOURCE_ROUTE_TABLE_SIZE: 254


  SL_IOSTREAM_USART_VCOM_BAUDRATE: 115200
  SL_IOSTREAM_USART_VCOM_RX_BUFFER_SIZE: 64
  SL_IOSTREAM_USART_VCOM_FLOW_CONTROL_TYPE: usartHwFlowControlCtsAndRts
  SL_IOSTREAM_USART_VCOM_PERIPHERAL: USART0
  SL_IOSTREAM_USART_VCOM_PERIPHERAL_NO: 0

  SL_IOSTREAM_USART_VCOM_TX_PORT: gpioPortA
  SL_IOSTREAM_USART_VCOM_TX_PIN:  6

  SL_IOSTREAM_USART_VCOM_RX_PORT: gpioPortA
  SL_IOSTREAM_USART_VCOM_RX_PIN:  5

  SL_IOSTREAM_USART_VCOM_CTS_PORT: gpioPortB
  SL_IOSTREAM_USART_VCOM_CTS_PIN:  1

  SL_IOSTREAM_USART_VCOM_RTS_PORT: gpioPortB
  SL_IOSTREAM_USART_VCOM_RTS_PIN:  0



